import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./utils/components/Providers";
import HamburgerMenu from "./utils/components/hamburgerMenu";
import RendezEviteLogo from "./utils/components/rendezEviteLogo";
import Footer from "./utils/components/footer";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { ISession } from "./utils/models/ISession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = (await getServerSession(authOptions)) as ISession;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main>
            <HamburgerMenu session={session} />
            <RendezEviteLogo />
            {children}
          </main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}

// TODO: Metataggar
